---
- hosts: servidores 
  become: yes
  tasks:
    - name: Install Nginx
      apt: 
        pkg: 
          - nginx
        state: present 
        update_cache: true

    - name: Install Python 3
      apt: pkg=python3-minimal state=present


#  ansible-playbook -i hosts  playbook/instalar_ngix.yml

