---
- name: comprobar el url de portainer
  uri:
    url: http://5.189.148.45:8080/ #"{{ url_portainer }}"
    url_username: "{{ username }}"
    url_password: "{{ password }}"
    force_basic_auth: yes
    status_code: [ -1, 200, 403, 503, 502 ]
  register: result 


- name: "debug resultado del chequeo"
  debug: 
    msg: "{{ result }}"

- set_fact:
    status_var: "{{result}}"

- name: status up
  debug:
    msg: "UP"
  when: result.status == 200


- name: status Down
  debug:
    msg: "Down"
  when: result.status == -1, 403, 503, 502


