---
# - name: mail status
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     # from: rachidmohamed072@gmail.com
#     to: bougaddara@gmail.com
#     username: bougaddara@gmail.com
#     password: 0668616234
#     subject: status of services
#     subtype: html
#     charsert: utf8
#     body: "{{ lookup( 'template', 'templates/status.html.jinja')}}"
#   # delegate_to: localhost
#   register: mail

# - debug:
#     msg: "{{ mail }}"


- name: email
  shell: cat ~/proyecto/ansible/roles/templates/deploy/status.html.jinja >> ~/proyecto/ansible/roles/templates/deploy/files/email.txt
  register: info_st

- debug:
    msg: "{{ info_st }}"