---
# - name: mail status
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     # from: rachidmohamed072@gmail.com
#     to: bougaddara@gmail.com
#     username: bougaddara@gmail.com
#     password: 0668616234
#     subject: status of services
#     subtype: html
#     charsert: utf8
#     body: "{{ lookup( 'template', 'templates/status.html.jinja')}}"
#   # delegate_to: localhost
#   register: mail

# - debug:
#     msg: "{{ mail }}"




- name: resultado de status
  lineinfile:
    path:  "~/proyecto/ansible/roles/deploy/files/email.txt"
    line: "- { 'date':'{{result.date}}', '{{ result.status }}' }"


