---
- name: mail status
  mail:
    host: localhost
    from: rachidmohamed072@gmail.com
    to: bougaddara@gmail.com
    subject: status of services
    subtype: html
    charser: utf8
    body: "{{ lookup( 'template', 'templates/status.html.jinja')}}"
  delegate_to: localhost
  register: mail

- debug:
    msg: "{{ mail }}"