---
- name: mail status
  mail:
    host: servidores
    from: rachidmohamed072@gmail.com
    to: bougaddara@gmail.com
    username: mohamed
    password: Mohamedrachid1.*
    subject: status of services
    subtype: html
    charser: utf8
    body: "{{ lookup( 'template', 'templates/status.html.jinja')}}"
  delegate_to: servidores
  register: mail

- debug:
    msg: "{{ mail }}"