---
- name: Install Nginx
  apt: 
    pkg: 
      - nginx
    state: present 
    update_cache: true
  notify: Start Nginx

- name: Install Python 3
  apt: pkg=python3-minimal state=present
 





# ansiblePlaybook becomeUser: 'mohamed', credentialsId: '5eeb5830-54b2-4065-bbae-a2df827b4535', disableHostKeyChecking: true, installation: 'ansible', inventory: 'ansible/hosts', playbook: 'ansible/playbook/deploy.yml'
