---
- name: Install Nginx
  apt: 
    pkg: 
      - nginx
    state: present 
    update_cache: true
  notify: Start Nginx

- name: Install Python 3
  apt: pkg=python3-minimal state=present
 


# local 
# ansiblePlaybook credentialsId: '2a45446b-8dc7-47e1-b798-38ffea110132', disableHostKeyChecking: true, installation: 'ansible', inventory: 'ansible/hosts', playbook: 'ansible/playbook/deploy.yml'


# sr

# ansiblePlaybook credentialsId: 'servidores', disableHostKeyChecking: true, installation: 'ansible', inventory: 'ansible/hosts', playbook: 'ansible/playbook/main.yml'